# Data from the web {#webdata}

The web is an amazing repository of data. Some of the pages don't change very often, while others are changing frequently. Some examples:

* The tables that tabulate the results of [the Labour Force Survey conducted by Statistics Canada](https://www150.statcan.gc.ca/n1/en/type/data?subject_levels=14&sourcecode=3701&freq=6#tables), including the unemployment rate in Canada and each province, are updated monthly.

* The [Billboard Hot 100 music chart](https://www.billboard.com/charts/hot-100) is updated weekly.

* The Environment Canada weather forecast page for [Victoria, British Columbia](https://weather.gc.ca/past_conditions/index_e.html?station=yyj) is updated every hour (as are the similar pages for 118 weather stations locations across British Columbia, and more across the rest of Canada). 



## APIs to access data

There are many data sources on the web.

One of the great things about the open source community is that people who have built tools to access that data in a streamlined and efficient way have made those tools available to the rest of us.

Here's some examples:

National Statistical Agencies:

{cansim} [@R-cansim]

{blscrapeR} [@R-blscrapeR]

Open data sites:

{bcdata}  [@R-bcdata]

{opendatatoronto} [@R-opendatatoronto]

{ropenaq} [@R-ropenaq]
 
