# Webscraping {#webscraping}

The web is an amazing repository of data. Some of the pages don't change very often, while others are changing frequently. Some examples:

* The tables that tabulate the results of [the Labour Force Survey conducted by Statistics Canada](https://www150.statcan.gc.ca/n1/en/type/data?subject_levels=14&sourcecode=3701&freq=6#tables), including the unemployment rate in Canada and each province, are updated monthly.

* The [Billboard Hot 100 music chart](https://www.billboard.com/charts/hot-100) is updated weekly.

* The Environment Canada weather forecast page for [Victoria, British Columbia](https://weather.gc.ca/past_conditions/index_e.html?station=yyj) is updated every hour (as are the similar pages for 118 weather stations locations across British Columbia, and more across the rest of Canada). 



See [@Gandrud_2015]


## Lesson: Introduction to webscraping

Library Carpentry, https://librarycarpentry.org/lc-webscraping/


## Lesson: 

Grant R. McDermott, _Big Data in Economics_ [@McDermott_BDE_2020]

* [Webscraping: (1) Server-side and CSS](https://raw.githack.com/uo-ec510-2020-spring/lectures/master/07-web-css/07-web-css.html)

* [Webscraping: (2) Client-side and APIs](https://raw.githack.com/uo-ec510-2020-spring/lectures/master/08-web-api/08-web-api.html)


## Other lessons

[Examples of Web Scraping With R](https://www.programmingr.com/examples/examples-web-scraping-r/)

[Web Scraping with R](https://www.scrapingbee.com/blog/web-scraping-r/) - ?


[Beginner’s Guide on Web Scraping in R (using rvest) with hands-on example](https://www.analyticsvidhya.com/blog/2017/03/beginners-guide-on-web-scraping-in-r-using-rvest-with-hands-on-knowledge/)

## {polite} package

https://dmi3kno.github.io/polite/index.html

[@R-polite]



## {rvest} package

[@R-rvest]


[@doi:10.1080/10691898.2020.1787116]




