# Data documentation {#documentation}

The data tables we receive will, we hope, come with some additional information. Names you might hear used include

* meta-data

* data documentation

* data dictionary

Wilson, Bryan et al. [@Wilson_Bryan_good_enough_2017]

## Data dictionary

A data dictionary contains a listing of all of the variables in the data set, along with the values and how they are coded. A good dictionary will also include additional reference materials, such as citations of sources and standards that are applied.

> A Data Dictionary is a collection of names, definitions, and attributes about data elements that are being used or captured in a database, information system, or part of a research project. It describes the meanings and purposes of data elements within the context of a project, and provides guidance on interpretation, accepted meanings and representation. A Data Dictionary also provides metadata about data elements. The metadata included in a Data Dictionary can assist in defining the scope and characteristics of data elements, as well the rules for their usage and application. 
[@UCMerced_data_dictionary]


Creating a data dictionary is often (or should be) part of a larger _data management plan_. This topic area is the specialization of information management experts, including librarians and archivists. The people in these disciplines have been thinking about these topics for literally centuries--data scientists can benefit and learn from this expertise.

Smithsonian: [Data Management Plans](https://library.si.edu/research/data-management-plans)

* [Describing Your Data: Data Dictionaries](https://library.si.edu/sites/default/files/tutorial/pdf/datadictionaries20180226.pdf)

* [Describing Your Project: Citation Metadata](https://library.si.edu/sites/default/files/tutorial/pdf/citationmetadata20180226.pdf)

University of New Hampshire [Data Management Toolkit @ UNH](https://libraryguides.unh.edu/datamanagement/metadata)

https://smithsonian.github.io/CCRCN-Public-Comment/data_management.html

https://www.lib.uiowa.edu/data/manage/documenting/readme/

https://library.usu.edu/data-management/data-management-plan

https://medium.com/@leapingllamas/data-dictionary-a-how-to-and-best-practices-a09a685dcd61

https://www.sas.com/en_us/whitepapers/data-management-for-analytics-best-practices-107769.html?utm_source=google&utm_medium=cpc&utm_campaign=dm-global&utm_content=GMS-44146&gclid=CjwKCAjwj975BRBUEiwA4whRB8uUDSFCbMOiy_lwXFBVH0gZxocQVi06iZftNfgzRj7QU4uaPeh7SxoCIfAQAvD_BwE

https://osf.io/vd4y3/download

https://rowman.com/isbn/9781442264380/data-management-a-practical-guide-for-librarians

https://www.clir.org/pubs/reports/pub154/problem-of-data/

https://guides.lib.umich.edu/c.php?g=538509&p=3686046

https://www.axiomdatascience.com/best-practices/DataManagementBestPractices.html

https://managing-qualitative-data.org/modules/2/a/

***

### In R

https://research.tue.nl/files/145367570/Data_Dictionary_Group_Tutorial.pdf

https://r4ds.had.co.nz/tidy-data.html#case-study

http://optimumsportsperformance.com/blog/creating-a-data-dictionary-function-in-r/

https://arxiv.org/pdf/2002.11626.pdf


{dataMeta}

https://bookdown.org/lyzhang10/lzhang_r_tips_book/how-to-make-a-simple-data-dictionary.html

https://cran.r-project.org/web/packages/dataMeta/vignettes/dataMeta_Vignette.html


{codebook}

https://www.rdocumentation.org/packages/codebook/versions/0.9.2

https://journals.sagepub.com/doi/full/10.1177/2515245919838783


