---
title: "weather stations"
output: html_notebook
---

Webscraping with rvest

https://stat4701.github.io/edav/2015/04/02/rvest_tutorial/

https://towardsdatascience.com/functions-with-r-and-rvest-a-laymens-guide-acda42325a77

https://www.r-bloggers.com/using-rvest-to-scrape-an-html-table/

https://www.analyticsvidhya.com/blog/2017/03/beginners-guide-on-web-scraping-in-r-using-rvest-with-hands-on-knowledge/

https://datamine.purdue.edu/seminars/spring2020/stat19000project07.html



Xpath syntax: https://www.w3schools.com/xml/xpath_intro.asp



## packages

```{r}

library(dplyr)

library(rvest)
library(xml2)

```

### LEGO movie example

http://rvest.tidyverse.org/articles/selectorgadget.html

```{r}
lego_url <- "https://www.imdb.com/title/tt1490017/"
html <- read_html(lego_url)

cast <- html_nodes(html, ".primary_photo+ td a")

length(cast)

cast[1:2]

```

```{r}

html_text(cast, trim = TRUE)

```





### Billboard example

https://github.com/keithmcnulty/scraping#basic-harvesting-the-billboard-hot-100-page


```{r}
hot100page <- "https://www.billboard.com/charts/hot-100"
hot100 <- read_html(hot100page)

hot100

str(hot100)

body_nodes <- hot100 %>% 
  html_node("body") %>% 
  html_children()

body_nodes

#body_nodes %>% 
#  html_children()

```

```{r}
rank <- hot100 %>% 
  rvest::html_nodes('body') %>% 
  xml2::xml_find_all("//span[contains(@class, 'chart-element__rank__number')]") %>% 
  rvest::html_text()

artist <- hot100 %>% 
  rvest::html_nodes('body') %>% 
  xml2::xml_find_all("//span[contains(@class, 'chart-element__information__artist')]") %>% 
  rvest::html_text()

title <- hot100 %>% 
  rvest::html_nodes('body') %>% 
  xml2::xml_find_all("//span[contains(@class, 'chart-element__information__song')]") %>% 
  rvest::html_text()

chart_df <- data.frame(rank, artist, title)

knitr::kable(
  chart_df  %>% head(10)
)

```


## Weather stations in British Columbia

This page has the hourly weather for the Environment Canada weather stations in British Columbia:

https://weather.gc.ca/provincialsummary_table/index_e.html?prov=bc&page=hourly



```{r}

ws_page_bc <- ("https://weather.gc.ca/provincialsummary_table/index_e.html?prov=bc&page=hourly")

ws_bc <- read_html(ws_page_bc)
ws_bc
str(ws_bc)

body_nodes <- ws_bc %>% 
 html_node("body") %>% 
 html_children()
body_nodes

```


<a href="/past_conditions/index_e.html?station=yxx" title="Display Past 24 Hour hourly observations for this station">Abbotsford Airport</a>

```{r}

stations <- html_nodes(ws_bc, "#hourtable a")

length(stations)

stations <- xml_nodes(ws_bc, "#hourtable_info , td:nth-child(1)")

# "a , #hourtable_info"

length(stations)

stations[1:2]
```


```{r}

xml_nodes(ws_bc, "#hourtable")


stations <- html_nodes(ws_bc, "#hourtable")

length(stations)

stations <- xml_node(ws_bc, "#hourtable")

length(stations)

```

//*[(@id = "hourtable")]

```{r}

# 

hourtable <- "//*[(@id = \"hourtable\")]"


html_nodes(ws_bc, xpath = hourtable)
xml_nodes(ws_bc, xpath = hourtable)

```



```{r}

html_nodes(ws_bc, xpath = "//*[(@id = \"hourtable\")]")

html_nodes(ws_bc, xpath = "//td[(((count(preceding-sibling::*) + 1) = 1) and parent::*)]")

html_nodes(ws_bc, xpath = "dataTables_wrapper no-footer")


html_nodes(ws_bc, xpath = "//td[(((count(preceding-sibling::*) + 1) = 1) and parent::*)] | //td[(((count(preceding-sibling::*) + 1) = 1) and parent::*)]//*[(@id = \"header1\")]")


html_nodes(ws_bc, "tr:nth-child(2) td")

html_nodes(ws_bc, xpath = "td:nth-child(1)")

```


```{r}

ws_bc %>% 
  html_nodes('body') %>% 
  xml_find_all("//div[contains(@id, 'hourly-container')]") %>% 
  html_text()


ws_bc %>% 
  html_nodes('body') %>% 
  xml_find_all("//*[(@id = '#hourtable')]") %>% 
  html_text()

ws_bc %>% 
  xml_nodes('#hourtable')


ws_bc %>% 
  html_nodes('body') %>% 
  xml_find_all("//*[(@id = '#hourtable')]") %>% 
  html_text()


ws_bc %>% 
  html_nodes('body') %>% 
  xml_find_all("//*[(@id = '#hourtable_wrapper')]") %>% 
  html_text()


ws_bc %>% 
  html_nodes('body') %>% 
  xml_find_all("//tr[(((count(preceding-sibling::*) + 1) = 55) and parent::*)]//td[(((count(preceding-sibling::*) + 1) = 1) and parent::*)]") %>% 
  html_text()

```

