# Collecting data

Before we can start analyzing data—and before we get to the "Import" step—we need to collect it.

And "collecting data" can mean a lot of different things. It could refer to data that is collected with the explicit purpose of supporting research:

* Running trials or experiments in a controlled laboratory setting, and collecting data with the results of those experiments. (Examples would include a chemistry lab and conducting medical tests on patients.)

* Making observations about the world and recording the results of those observations (for example, as an astronomer, biologist, or geographer might).

* Sampling the people in an area and asking them a series of questions. (This is common in marketing, human resources, and sociology.)

It can also refer to data that comes from secondary sources; that is to say, it is collected for a purpose distinct from the research questions, but can be used to answer those questions.

* Collecting information as part of a business operation. A familiar example are supermarket checkout scanners which data about grocery purchases. The primary purpose of this data collection is to facilitate operation management of the store by tracking sales and inventory, and generating orders. But it can also be used to answer questions about store staffing (what time of day are most customers shopping?), 

* Downloading data from a website, where the downloaded table has data that has already been compiled and summarized from a larger data set. An example would be Statistics Canada's Census data tables.

And it's important to note that your analysis project might require more than one of these methods of data collection.

How you collect the data you need will depend on many factors, including what is already available, what your budget is (some data collection methods will cost a lot more than others), and the legal and regulatory environment you are operating in (for example, the definition of "personal information" varies from one jurisdiction to the next).

The complexities of data collection are outside the scope of this book, but


