---
title: "weather stations"
output: html_notebook
---

Webscraping with rvest


Xpath syntax: https://www.w3schools.com/xml/xpath_intro.asp



## packages

```{r}

library(dplyr)

library(rvest)
library(xml2)

```



## Weather stations in British Columbia

This page has the hourly weather for the Environment Canada weather stations in British Columbia:

https://weather.gc.ca/provincialsummary_table/index_e.html?prov=bc&page=hourly



```{r}

ws_page_bc <- ("https://weather.gc.ca/provincialsummary_table/index_e.html?prov=bc&page=hourly")

ws_bc <- read_html(ws_page_bc)
ws_bc
str(ws_bc)

body_nodes <- ws_bc %>% 
 html_node("body") %>% 
 html_children()
body_nodes

```




<a href="/past_conditions/index_e.html?station=yxx" title="Display Past 24 Hour hourly observations for this station">Abbotsford Airport</a>

```{r}

stations <- html_nodes(ws_bc, "#hourtable a")

length(stations)

stations <- xml_nodes(ws_bc, "#hourtable_info , td:nth-child(1)")

# "a , #hourtable_info"

length(stations)

stations[1:2]
```


```{r}
stations <- xml_nodes(ws_bc, ".table", "hourtable_info", "td:nth-child(1)")

# "a , #hourtable_info"

length(stations)

stations[1:2]

```


```{r}

xml_nodes(ws_bc, "#hourtable")


stations <- html_nodes(ws_bc, "#hourtable")

length(stations)

stations <- xml_node(ws_bc, "#hourtable")

length(stations)

```

//*[(@id = "hourtable")]
//*[(@id = "hourtable")]

```{r}

# 

hourtable <- "//*[(@id = \"hourtable\")]"


html_nodes(ws_bc, xpath = hourtable)
xml_nodes(ws_bc, xpath = hourtable)

html_text(ws_bc, xpath = hourtable)

```



```{r}

html_nodes(ws_bc, xpath = "//*[(@id = \"hourtable\")]")

html_nodes(ws_bc, xpath = "//td[(((count(preceding-sibling::*) + 1) = 1) and parent::*)]")

html_nodes(ws_bc, xpath = "dataTables_wrapper no-footer")


html_nodes(ws_bc, xpath = "//td[(((count(preceding-sibling::*) + 1) = 1) and parent::*)] | //td[(((count(preceding-sibling::*) + 1) = 1) and parent::*)]//*[(@id = \"header1\")]")


html_nodes(ws_bc, "tr:nth-child(2) td")

html_nodes(ws_bc, xpath = "td:nth-child(1)")

```


```{r}

ws_bc %>% 
  html_nodes('body') %>% 
  xml_find_all("//div[contains(@id, 'hourly-container')]") %>% 
  html_text()


ws_bc %>% 
  html_nodes('body') %>% 
  xml_find_all("//*[(@id = '#hourtable')]") %>% 
  html_text()

ws_bc %>% 
  xml_nodes('#hourtable')


ws_bc %>% 
  html_nodes('body') %>% 
  xml_find_all("//*[(@id = '#hourtable')]") %>% 
  html_text()


ws_bc %>% 
  html_nodes('body') %>% 
  xml_find_all("//*[(@id = '#hourtable_wrapper')]") %>% 
  html_text()


ws_bc %>% 
  html_nodes('body') %>% 
  xml_find_all("//tr[(((count(preceding-sibling::*) + 1) = 55) and parent::*)]//td[(((count(preceding-sibling::*) + 1) = 1) and parent::*)]") %>% 
  html_text()

```


```{r}
ws_bc %>% 
  html_nodes('body') %>% 
  xml_find_all("//tr") 



```


```{r}

ws_bc %>%
  html_nodes(".headers") %>% 
  html_text()

```

```{r}

xml_path(ws_bc, xml_find_all("//tr[(((count(preceding-sibling::*) + 1) = 1) and parent::*)]//td[(((count(preceding-sibling::*) + 1) = 1) and parent::*)] | //*[(@id = \\\"hourtable\\\")]"))

xml_path(ws_bc, xml_find_all(".header1"))



```

